### ISSUE TITLE
Backup generates a .ab file with Windows line endings

### ISSUE THREAD

**Issue by ehcloninger** [Own-Data-Privateer/hoardy-adb#4]
I'm not sure if this is an issue with the backup process in adb or something you can handle in the hyadb code base itself.

I backed up my Galaxy Tab S6 today using `hyadb backup` on Windows 11 under Powershell. The adb on the path is version 35.0.2 from September 2024. Immediately after downloading the .ab file, I tried `hyadb list backup-2025-10-20.ab` and was given an error that the file is not an Android backup file. So, I forked the repo and started debugging.

The problem exists at line 392 in __main__.py, where it's confirming the input file has the correct header signature. The code expects line 1 of the input to read **ANDROID BACKUP**, which it does. Except the line endings are \0d\0a, so the \0d is interpreted as part of the string. I forced the debugger past the check and the other places where it's using `readline()` and comparing the output also has \0d as part of the string.

I dumped the output using xxd under WSL Ubuntu and confirmed there the file has many \0d\0a sequences.

```/mnt/c/dev/tabs6$ xxd backup_2025-10-20.ab | more
00000000: 414e 4452 4f49 4420 4241 434b 5550 0d0a  ANDROID BACKUP..
00000010: 350d 0a31 0d0a 4145 532d 3235 360d 0a32  5..1..AES-256..2
00000020: 3336 4435 4243 3333 4437 3331 3742 4642  36D5BC33D7317BFB
00000030: 4337 3931 3638 3042 3039 4335 3946 3541  C791680B09C59F5A
```
I moved over to an actual Linux machine and installed adb over there. When I issued `hyadb backup` on the same tablet, the .ab file only has line feeds.

```/dev/tabs6$ xxd backup_2025-10-20.ab | more
00000000: 414e 4452 4f49 4420 4241 434b 5550 0a35  ANDROID BACKUP.5
00000010: 0a31 0a41 4553 2d32 3536 0a32 4239 3237  .1.AES-256.2B927
00000020: 3038 3331 3933 3845 3345 3231 4341 3241  0831938E3E21CA2A
00000030: 4135 3739 3932 3245 3937 3830 3046 4536  A579922E97800FE6
```
Is this a problem with the adb client side on Windows or is it something that can be controlled in hyadb?

**Comment by oxij** [comment]
Thanks for the report!

What's your

```
python --version
```

?

If you do

```
adb shell bu backup -apk -obb -all -keyvalue -nosystem > backup.ab
```

manually in Powershell, does the resulting file have those newlines?

**Comment by ehcloninger** [comment]
> python --version

3.13.5

> adb shell bu backup -apk -obb -all -keyvalue -nosystem > backup.ab

Oh, that gets even more interesting. It's UTF-8...

```
00000000: fffe 4100 4e00 4400 5200 4f00 4900 4400  ..A.N.D.R.O.I.D.
00000010: 2000 4200 4100 4300 4b00 5500 5000 0d00   .B.A.C.K.U.P...
00000020: 0a00 3500 0d00 0a00 3100 0d00 0a00 4100  ..5.....1.....A.
00000030: 4500 5300 2d00 3200 3500 3600 0d00 0a00  E.S.-.2.5.6.....
00000040: 3700 4400 3400 3300 3500 4600 3100 4400  7.D.4.3.5.F.1.D.
00000050: 3900 3800 3600 3400 4400 4500 3200 3500  9.8.6.4.D.E.2.5.
```

Target is a Galaxy Tab S6, running Android 12 (OneUI 4.1.1). It's stock, unrooted. Kernel is 4.14.190. 

Host system is Windows 11. 
Powershell 5.1.26100.6899

This isn't a big issue. I thought I might install LineageOS on this tablet as some of the software is starting to fail. Turns out, nobody has a LineageOS build for this device at all. Not even homegrown ROM on XDA. So, perhaps I'll just upgrade to a newer tablet instead.

Happy to help debug this if it's a wider issue. I have the repo forked and I can step-wise debug in VS Code. I'm a bit surprised it hasn't shown up before, but maybe all the people using hyadb are sensible folks using Linux or MacOS. ;-)

**Comment by oxij** [comment]
> Oh, that gets even more interesting. It's UTF-8...

That looks like UTF-16 to me. Is that dump from `xdd` under WSL Ubuntu
still? If so, then it look like `adb` thinks it's working with a
terminal while dumping to a file.

Does any of the following produce the right result?

```
adb shell -T bu backup -apk -obb -all -keyvalue -nosystem > backup1.ab
adb shell -nT bu backup -apk -obb -all -keyvalue -nosystem > backup2.ab
```

**Comment by ehcloninger** [comment]
Yes, I dumped it under WSL Ubuntu, but generated it from Windows Powershell. I've since installed xxd using choco and all the dumps on this message were generated from Powershell.

```
> adb shell -T bu backup -apk -obb -all -keyvalue -nosystem > .\backup1.ab
> xxd -l 128 .\backup1.ab
00000000: fffe 4100 4e00 4400 5200 4f00 4900 4400  ..A.N.D.R.O.I.D.
00000010: 2000 4200 4100 4300 4b00 5500 5000 0d00   .B.A.C.K.U.P...
00000020: 0a00 3500 0d00 0a00 3100 0d00 0a00 4100  ..5.....1.....A.
00000030: 4500 5300 2d00 3200 3500 3600 0d00 0a00  E.S.-.2.5.6.....
00000040: 4600 3800 3700 3200 4100 3400 4100 3700  F.8.7.2.A.4.A.7.
00000050: 3500 3000 4500 3700 4100 4100 3700 3400  5.0.E.7.A.A.7.4.

> adb shell -nT bu backup -apk -obb -all -keyvalue -nosystem > backup2.ab
> xxd -l 128 .\backup2.ab
00000000: fffe 4100 4e00 4400 5200 4f00 4900 4400  ..A.N.D.R.O.I.D.
00000010: 2000 4200 4100 4300 4b00 5500 5000 0d00   .B.A.C.K.U.P...
00000020: 0a00 3500 0d00 0a00 3100 0d00 0a00 4100  ..5.....1.....A.
00000030: 4500 5300 2d00 3200 3500 3600 0d00 0a00  E.S.-.2.5.6.....
00000040: 3100 4600 3700 4500 3600 4100 3500 4400  1.F.7.E.6.A.5.D.
00000050: 3100 3700 4400 4100 3800 3900 3500 4100  1.7.D.A.8.9.5.A.
```

As I mentioned earlier, I can get a working .ab file using my dedicated Linux machine, but this is definitely odd. If you don't have any ability to deal with it in your code base, you could just make a note about using backups from Windows. I don't know if this is something Google did in the adb server on the host or if it's something bizarre from Powershell.

BTW, if you want to chat in more-or-less real time, my Discord handle is the same as Github. I'm in UTC-5:00 (Central US).

**Comment by oxij** [comment]
> As I mentioned earlier, I can get a working .ab file using my dedicated Linux machine, but this is definitely odd. If you don't have any ability to deal with it in your code base, you could just make a note about using backups from Windows. I don't know if this is something Google did in the adb server on the host or if it's something bizarre from Powershell.

Well, to me it looks like `adb shell` always tries to output to a terminal on Windows, even when outputting to a file.
It's just `cmd.exe` (which is what Python uses to run stuff) and `PowerShell` probably setup different output encodings.

I've looked at `adb` sources at <https://android.googlesource.com/platform/packages/modules/adb> and it appears to be exactly that.
So, a proper solution would be to patch `adb shell` to take a `--raw` option or something similar.

But, for now, as a workaround, it seems like

```
adb backup -f backup3.ab -apk -obb -all -keyvalue -nosystem
```

should still work as expected, even though it's deprecated.
Does it?
If it does, I can simply patch `hyadb backup` to use that on Windows.

(As to Discord, having this documented in a permanent way is better.)

**Comment by ehcloninger** [comment]
Yes, that command does work. It seems very strange to output a file with host-specific line endings in the header when the rest of the file is binary.

```
> xxd -l 128 .\backup3.ab
00000000: 414e 4452 4f49 4420 4241 434b 5550 0a35  ANDROID BACKUP.5
00000010: 0a31 0a41 4553 2d32 3536 0a34 3942 4344  .1.AES-256.49BCD
00000020: 3434 3032 3933 3145 3241 3235 3531 3142  4402931E2A25511B
00000030: 3942 3239 3738 3833 3031 4645 4639 4339  9B29788301FEF9C9
00000040: 4336 4645 3039 3745 3741 3143 3745 4134  C6FE097E7A1C7EA4
00000050: 3637 4138 3034 4441 4337 3043 3031 3743  67A804DAC70C017C
```

**Comment by oxij** [comment]
> Yes, that command does work.

Nice.

> It seems very strange to output a file with host-specific line endings in the header when the rest of the file is binary.

My guess would be that the rest of that file also has all LF chars replaced with CRLF.

Now that I think about it, `hyadb backup-apks` and others would probably also need some work-arounds to handle those CRLFs.
I wonder if it's maybe possible to force raw mode from outside of the process somehow instead.

This needs some research and consideration.

**Comment by oxij** [comment]
I think I fixed this and related issues in v2.0.1. Please confirm.

**Comment by thehydroreview** [comment]
Hi @oxij 

I confirm this change works on Windows 11 under Powershell. The .ab file has the correct line endings and I can run other operations on the resulting file. 

One minor problem still exists and I will open a new issue on that.

**Comment by ehcloninger** [comment]
@oxij Sorry about that, the previous comment was me, but logged into a project account.

**Comment by oxij** [comment]
Ok, thanks!
